Shellcheck cleaned scripts + made some scripts niri compatible

diff --git a/private_dot_local/bin/watcher.d/executable_xdg b/private_dot_local/bin/watcher.d/executable_xdg
--- a/private_dot_local/bin/watcher.d/executable_xdg
+++ b/private_dot_local/bin/watcher.d/executable_xdg
@@ -10,15 +10,15 @@
 
 # --- Base set up -----------------------------------------------------------------------
 
-source "$HOME/.config/shell/lib/format"
+source "$XDG_CONFIG_HOME/shell/lib/format"
 
 script_name=$(basename "$0")
 
-CONFIG_BASELINE=$HOME/.local/share/watcher/xdg/config-baseline.txt
-STATE_BASELINE=$HOME/.local/share/watcher/xdg/state-baseline.txt
-SHARE_BASELINE=$HOME/.local/share/watcher/xdg/share-baseline.txt
-CACHE_BASELINE=$HOME/.local/share/watcher/xdg/cache-baseline.txt
-HOME_BASELINE=$HOME/.local/share/watcher/xdg/home-baseline.txt
+CONFIG_BASELINE=$XDG_DATA_HOME/watcher/xdg/config-baseline.txt
+STATE_BASELINE=$XDG_DATA_HOME/watcher/xdg/state-baseline.txt
+SHARE_BASELINE=$XDG_DATA_HOME/watcher/xdg/share-baseline.txt
+CACHE_BASELINE=$XDG_DATA_HOME/watcher/xdg/cache-baseline.txt
+HOME_BASELINE=$XDG_DATA_HOME/watcher/xdg/home-baseline.txt
 
 DESC="Monitor xdg directories"
 
@@ -57,22 +57,22 @@ display_diff() {
 
 if [[ $# -eq 0 ]]; then
 	subsection "      .config      "
-	DIFF_OUTPUT=$(diff <(cat $CONFIG_BASELINE) <(/usr/bin/ls -1 ~/.config/))
+	DIFF_OUTPUT=$(diff <(cat "$CONFIG_BASELINE") <(/usr/bin/ls -1 ~/.config/))
 	display_diff "$DIFF_OUTPUT"
 
 	subsection "    .local/state   "
-	DIFF_OUTPUT=$(diff <(cat $STATE_BASELINE) <(/usr/bin/ls -1 ~/.local/state/))
+	DIFF_OUTPUT=$(diff <(cat "$STATE_BASELINE") <(/usr/bin/ls -1 ~/.local/state/))
 	display_diff "$DIFF_OUTPUT"
 
 	subsection "    .local/share   "
-	DIFF_OUTPUT=$(diff <(cat $SHARE_BASELINE) <(/usr/bin/ls -1 ~/.local/share/))
+	DIFF_OUTPUT=$(diff <(cat "$SHARE_BASELINE") <(/usr/bin/ls -1 ~/.local/share/))
 	display_diff "$DIFF_OUTPUT"
 
 	subsection "       .cache      "
-	DIFF_OUTPUT=$(diff <(cat $CACHE_BASELINE) <(/usr/bin/ls -1 ~/.cache/))
+	DIFF_OUTPUT=$(diff <(cat "$CACHE_BASELINE") <(/usr/bin/ls -1 ~/.cache/))
 	display_diff "$DIFF_OUTPUT"
 
-	DIFF_OUTPUT=$(diff <(cat $HOME_BASELINE) <(/usr/bin/ls -1a $HOME))
+	DIFF_OUTPUT=$(diff <(cat "$HOME_BASELINE") <(/usr/bin/ls -1a "$HOME"))
 	if [[ -n "$DIFF_OUTPUT" ]]; then
 		subsection "       home      "
 		ADDITIONS=$(echo "$DIFF_OUTPUT" | grep "^>" | sed 's/^> /+ /')
@@ -91,15 +91,15 @@ elif [[ $# -eq 1 ]]; then
 			-h|--help) show_help ;;
 			update)
 				if gum confirm "Confirm XDG baseline update"; then
-					/usr/bin/ls -1 "$HOME/.config" > $CONFIG_BASELINE
-					/usr/bin/ls -1 "$HOME/.local/state" > $STATE_BASELINE
-					/usr/bin/ls -1 "$HOME/.local/share" > $SHARE_BASELINE
-					/usr/bin/ls -1 "$HOME/.cache" > $CACHE_BASELINE
-					/usr/bin/ls -1a "$HOME" > $HOME_BASELINE
+					/usr/bin/ls -1 "$HOME/.config" > "$CONFIG_BASELINE"
+					/usr/bin/ls -1 "$HOME/.local/state" > "$STATE_BASELINE"
+					/usr/bin/ls -1 "$HOME/.local/share" > "$SHARE_BASELINE"
+					/usr/bin/ls -1 "$HOME/.cache" > "$CACHE_BASELINE"
+					/usr/bin/ls -1a "$HOME" > "$HOME_BASELINE"
 				fi
 				break
 				;;
-			*) echo echo "error: invalid command '$1'"; exit 1 ;;
+			*) echo "error: invalid command '$1'"; exit 1 ;;
 		esac
 	done
 
